### PR TITLE
create es6 module

### PR DESCRIPTION
**Pull request by amaldare93**
I have made a new file that is identical to `arc.js`, but has ES6 module exports so that it will be compatible with ES6 bundlers such as [Rollup.js](http://rollupjs.org/).

I have also added `jsnext:main:` to the package.json. This is so that Rollup can find the ES6 module file; other module loaders will still read from the main file, and should be unaffected by these changes.

### CODE REVIEW

**Comment by springmeyer** [comment]
Thanks for this contribution. Can you think of a way to avoid the code duplication?

**Comment by amaldare93** [comment]
Yes, I will try to look for a way to shove it in the main file into that
conditional at the end maybe.

I'll get back to you tomorrow about it.

**Comment by amaldare93** [comment]
Hey, sorry for the delay, i spent the last 4 days working on a way to automate the es6 module generation, and then i realized that #26 alone fixes my original problem (requiring arc in Rollup) and i noticed that even though it was merged in November, it was never published to npm. Would it be possible for you to publish the latest version of Arc to npm? 

If there is some reason you don't want to do that, I suppose i can try to npm install from the git repo, but I'm sure many others would benefit from the publishing.

**Comment by daumann** [comment]
@springmeyer any updates on this? Could you publish the ES6 ready version (necessary also for react/ webpack setup)?

**Comment by springmeyer** [comment]
@daumann as far as I can tell there is no need for this given:

> then i realized that #26 alone fixes

Looks like I just need to publish a new version. Sound good?

**Comment by springmeyer** [comment]
#26 is now published in `arc@0.1.1`

**Pull request closed without merging**
