### PR TITLE
Support browserify by using UMD

### PR DESCRIPTION
**Pull request by abuchanan**
I found that arc wasn't loading when I was using browserify, so I moved the module to a [UMD](https://github.com/umdjs/umd/blob/master/templates/returnExports.js) style definition.

### CODE REVIEW

**Comment by tmcw** [comment]
This shouldn't be necessary; the `window` check for arc's exports needs a much smaller tweak

**Comment by abuchanan** [comment]
UMD is a well known concept, with lots of thought behind it, for a reason, including isolating the module code from the global scope.

**Comment by tmcw** [comment]
I don't disagree with UMD, but I know that this is the wrong way to solve this problem. The "is this a browser" [check](https://github.com/springmeyer/arc.js/pull/27/files#diff-95085184866ad51bc3d02248a7f4cd7eL249) was broken, and needs a one-line fix.

**Comment by tmcw** [comment]
Fixed by https://github.com/springmeyer/arc.js/pull/26

**Pull request closed without merging**
