### PR TITLE
update leaflet to 1.8.0 to fix demo in Safari

### LINKED ISSUE #46: Demo site hits javascript error with Safari
I just noticed that the demo site works for me in Chrome, but not Safari (on a Mac).

One point is able to be plotted, but not a second (so no arc is drawn). The error in the console is:

```
Error: Invalid LatLng object: (NaN, NaN)
```

Screen Shot 2022-07-08 at 8 04 06 PM

Don't have time to debug this right now, so just filing the ticket as a reminder in case I find time in the future to debug, or others do.

### PR DESCRIPTION
**Pull request by jgravois**
resolves #46

ref: https://github.com/Leaflet/Leaflet/issues/7255

### CODE REVIEW

**Comment by springmeyer** [comment]
Thanks!

**Comment by jgravois** [comment]
no worries at all. your issue reminded me i had a few `TODO:`s of my own. 🙏

**Comment by Nicocaputocai** [comment]
Hi! i update to leaflet 1.9 and i cant see my layers. Any solution?

**Comment by jgravois** [comment]
i know 1.9 included some breaking changes. if you can share a simplified repro case that shows exactly what the issue is that'd make it more convenient to track down the problem.

**Comment by Nicocaputocai** [comment]
This is my app. Works ok on all devices except ios

mapa.desarrolloi.org/

My repo 

https://github.com/Nicocaputocai/LanusInteligenteMapa

I worked with GeoJSON files

**Comment by jgravois** [comment]
by 'repro case', i mean sharing the bare minimum of code necessary to display the problem you're seeing.

this library doesn't do anything in the way of 'drawing', so if you aren't seeing GeoJSON files in iOS only. it'd be worth whittling things down to confirm that its not a problem with Leaflet itself.

**Comment by Nicocaputocai** [comment]
Oh, sorry. I speak English a little.

Here i create the popups

function onEachFeature(feature, layer) {
  // does this feature have a property named popupContent?
  if (feature.properties && feature.geometry.type != "Polygon") {
  return layer.bindPopup(
    `<h3>${feature.properties.name}</h3><span>Dirección: ${feature.properties.address} ${feature.properties.height}</span>`
  );
 }else if (feature.properties && feature.geometry.type == "Polygon"){
  return layer.bindPopup(
    `<h3>${feature.properties.name}</h3><span>Dirección: ${feature.properties.address}</span>`
  )
 }
}


async function setMap(arr) {
  var map = L.map("map", {
    center: [-34.7033363, -58.3953235],
    zoom: 13,
	"tap": false
  });

One example

var health = L.geoJSON(healthData, {
          onEachFeature: onEachFeature,
          pointToLayer: function (feature, latlng) {
            if (feature.properties.dependence == "Municipal") {
              return L.marker(latlng, { icon: healthIconMunicipal });
            } else if (feature.properties.dependence == "Provincial") {
              return L.marker(latlng, { icon: healthIconProvincial });
            } else {
              return L.marker(latlng, { icon: healthIconPrivate });
            }
          },

var overLayers = {
          Clubes: club,
          "Dependencias Municipales": MunicipalDependence,
          "Educación Inicial": initialEducation,
          "Escuelas Primarias": primaryEducation,
          "Escuelas Secundarias": hightSchollEducation,
          "Escuelas Técnicas": tecnicalHightSchollEducation,
          Universidades: universityEducation,
          "Otros establecimientos educativos": otherEducation,
          "Parques y plazas": squareAndPark,
          Salud: health,
          "Seguridad y Justicia": security,
          Transporte: transport,
        };

L.control.layers(overLayers, baseMap).addTo(map);


        })

return arr;

**Comment by jgravois** [comment]
none of the code you shared comes from arc.js so there's not much we can do about your problem here.

https://github.com/springmeyer/arc.js#api

**Pull request merged**
